local ScreenGui = Instance.new("ScreenGui", game.CoreGui)
ScreenGui.ScreenInsets = 0

local TextLabel = Instance.new("TextLabel")
TextLabel.Size = UDim2.new(1, 0, 1, 0)
TextLabel.Text = "Holy skid!! if you are Akira690 reading this, fuck off\n24HRS Discord: https://discord.gg/bjTxKxjJVc"
TextLabel.TextColor3 = Color3.new(1, 1, 1)
TextLabel.TextScaled = true
TextLabel.Font = "Code"
TextLabel.BackgroundTransparency = 1
TextLabel.Parent = ScreenGui
